"""Configuration for the retained ROI Ensemble inference pipeline."""

from pathlib import Path


EXPERT_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = EXPERT_DIR.parent
RESOURCES_DIR = PROJECT_ROOT / "resources"
FACE_MODELS_DIR = RESOURCES_DIR / "face_models"

HAAR_CASCADE_PATH = FACE_MODELS_DIR / "haarcascade_frontalface_default.xml"
LBF_MODEL_PATH = FACE_MODELS_DIR / "lbfmodel.yaml"
EXPRESSION_ZIP = RESOURCES_DIR / "expression_data" / "facial_expression_dataset.zip"

DATA_DIR = EXPERT_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "input" / "raw"
MODELS_DIR = EXPERT_DIR / "models" / "roi_ensemble"
RESULTS_DIR = EXPERT_DIR / "results" / "roi_ensemble"
OUTPUTS_DIR = EXPERT_DIR / "outputs" / "runtime"

CLASSES = ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
SPLITS = ["train", "test"]
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}

ROI_CNN_VARIANTS = ["face", "face_eyes", "face_eyes_mouth", "face_eyes_mouth_aux"]
ROI_CNN_DEMO_VARIANT = "face_eyes_mouth"
ROI_CNN_DEMO_MODEL_FILE = MODELS_DIR / "base" / "best_roi_cnn_face_eyes_mouth.pth"
ROBUST_ROI_CNN_MODEL_FILE = MODELS_DIR / "robust" / "robust_roi_cnn_face_eyes_mouth.pth"
ROI_ENSEMBLE_CONFIG_FILE = MODELS_DIR / "ensemble_config.json"
ROI_ENSEMBLE_BASE_WEIGHT = 0.45
ROI_ENSEMBLE_ROBUST_WEIGHT = 0.55
ROI_CNN_EYE_BROW_PADDING = 0.22
ROI_CNN_NOSE_MOUTH_PADDING = 0.20

CNN_INPUT_SIZE = 48
CNN_NORMALIZATION_MEAN = 0.5
CNN_NORMALIZATION_STD = 0.5
CNN_DROPOUT = 0.4

CAMERA_INDEX = 0
DEMO_WINDOW_NAME = "ROI Ensemble Expression Effects"
QUIT_KEY = "q"
REALTIME_DEFAULT_MAX_FACES = 1
REALTIME_SHOW_POSE_LABEL = False
UNCERTAIN_LABEL = "uncertain"

PREDICTION_HISTORY_SIZE = 5
MIN_PREDICTION_CONFIDENCE = 0.30
MIN_PREDICTION_MARGIN = 0.03
MIN_STABLE_FRAMES = 3
REALTIME_PREDICT_EVERY_N_FRAMES = 2
REALTIME_PROBABILITY_EMA_ALPHA = 0.45
REALTIME_NEUTRAL_TO_EXPRESSION_FRAMES = 3
REALTIME_EXPRESSION_TO_NEUTRAL_FRAMES = 5
REALTIME_EXPRESSION_SWITCH_FRAMES = 4

REALTIME_BOX_SMOOTHING_ALPHA = 0.25
REALTIME_LANDMARK_ALPHA_JAW = 0.12
REALTIME_LANDMARK_ALPHA_BROW_NOSE = 0.22
REALTIME_LANDMARK_ALPHA_EYES_MOUTH = 0.34
REALTIME_LANDMARK_MAX_POINT_JUMP_RATIO = 0.16
REALTIME_LANDMARK_JAW_MAX_POINT_JUMP_RATIO = 0.055
REALTIME_JAW_BOUND_MARGIN_X = 0.08
REALTIME_JAW_BOUND_TOP_RATIO = 0.10
REALTIME_JAW_BOUND_BOTTOM_RATIO = 1.08
REALTIME_DISPLAY_POSE_CONTOUR_START_YAW = 8.0
REALTIME_DISPLAY_POSE_CONTOUR_FULL_YAW = 35.0
REALTIME_DISPLAY_POSE_CONTOUR_MAX_SHRINK = 0.28
REALTIME_DISPLAY_POSE_CONTOUR_Y_LIFT = 0.06
REALTIME_DISPLAY_LANDMARK_ALPHA = 0.28
REALTIME_DISPLAY_JAW_ALPHA = 0.13
REALTIME_LANDMARK_RESET_CENTER_SHIFT = 0.35
REALTIME_LANDMARK_RESET_AREA_RATIO = 0.55
REALTIME_LANDMARK_RESET_EYE_ANGLE_DEGREES = 18.0
REALTIME_MAX_CACHED_FRAMES = 3
REALTIME_MIN_FACE_AREA_RATIO = 0.018
REALTIME_MIN_FACE_ASPECT = 0.70
REALTIME_MAX_FACE_ASPECT = 1.45
REALTIME_MAX_MATCH_DISTANCE = 110.0
REALTIME_MIN_MATCH_IOU = 0.12
REALTIME_REJECT_INNER_FACE_AREA_RATIO = 0.45
REALTIME_FACE_EXPAND_X = 0.15
REALTIME_FACE_EXPAND_TOP = 0.18
REALTIME_FACE_EXPAND_BOTTOM = 0.15
REALTIME_LBF_EXPAND_X = 0.03
REALTIME_LBF_EXPAND_TOP = 0.04
REALTIME_LBF_EXPAND_BOTTOM = 0.03
REALTIME_USE_ROI_TRACKING = True
REALTIME_ROI_EXPAND_X = 0.45
REALTIME_ROI_EXPAND_TOP = 0.45
REALTIME_ROI_EXPAND_BOTTOM = 0.45
REALTIME_ROI_MIN_FACE_SCALE = 0.55
REALTIME_ROI_MAX_RESULTS_PER_TRACK = 2
REALTIME_FULL_DETECT_INTERVAL = 10
REALTIME_DETECTION_DEDUPE_IOU = 0.35

HEAD_POSE_SMOOTHING_ALPHA = 0.25
HEAD_POSE_YAW_THRESHOLD = 25.0
HEAD_POSE_PITCH_THRESHOLD = 22.0
HEAD_POSE_INVERT_YAW = False
HEAD_POSE_INVERT_PITCH = True

REALTIME_FACE_SCALE_FACTOR = 1.1
REALTIME_FACE_MIN_NEIGHBORS = 5
REALTIME_FACE_MIN_SIZE = (80, 80)
REALTIME_PREPROCESS_MODE = "clahe"
REALTIME_GAMMA_VALUE = 1.25
REALTIME_CLAHE_CLIP_LIMIT = 2.0
REALTIME_CLAHE_TILE_GRID = (8, 8)

FER_UPSCALE = 3
FER_DETECTION_STRATEGIES = [
    {"name": "clahe_x3_balanced", "upscale": 3, "preprocess": "clahe", "scaleFactor": 1.08, "minNeighbors": 4, "minSize": (24, 24)},
    {"name": "clahe_x3_sensitive", "upscale": 3, "preprocess": "clahe", "scaleFactor": 1.05, "minNeighbors": 3, "minSize": (20, 20)},
    {"name": "gray_x4_sensitive", "upscale": 4, "preprocess": "gray", "scaleFactor": 1.05, "minNeighbors": 3, "minSize": (24, 24)},
    {"name": "clahe_x4_sensitive", "upscale": 4, "preprocess": "clahe", "scaleFactor": 1.04, "minNeighbors": 3, "minSize": (24, 24)},
    {"name": "gray_x5_last_resort", "upscale": 5, "preprocess": "gray", "scaleFactor": 1.04, "minNeighbors": 2, "minSize": (28, 28)},
]
