"""Beginner Level configuration."""

from pathlib import Path


BEGINNER_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BEGINNER_DIR.parent

HAAR_CASCADE_PATH = PROJECT_ROOT / "resources" / "face_models" / "haarcascade_frontalface_default.xml"
YUNET_MODEL_PATH = PROJECT_ROOT / "resources" / "face_models" / "face_detection_yunet_2023mar.onnx"
LBF_MODEL_PATH = PROJECT_ROOT / "resources" / "face_models" / "lbfmodel.yaml"

CAMERA_INDEX = 0
WINDOW_NAME = "Beginner Face Landmarks"
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
QUIT_KEY = "q"
UNMIRROR_CAMERA = True

# More conservative Haar settings to reduce nose/mouth false positives.
FACE_SCALE_FACTOR = 1.05
FACE_MIN_NEIGHBORS = 5
FACE_MIN_SIZE = (80, 80)
FACE_MAX_SIZE = (420, 420)
FACE_DETECTION_DEDUPE_IOU = 0.35
FULL_DETECT_INTERVAL = 10
BOX_SMOOTHING_ALPHA = 0.25

USE_CLAHE = False
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID_SIZE = (8, 8)
PREPROCESS_MODE = "clahe"
GAMMA_VALUE = 1.25
ENHANCE_VIDEO_FRAME = False
SHOW_FACE_POSE_LABELS = False
LOW_LIGHT_GAMMA_VALUE = 1.32
LOW_LIGHT_CLAHE_CLIP_LIMIT = 1.6
LOW_LIGHT_BLEND_ALPHA = 0.62
LOW_LIGHT_MEAN_THRESHOLD = 95.0
LOW_LIGHT_SHARPEN_AMOUNT = 0.35

PADDING_RATIO = 0.15
MAX_FACE_HOLD_FRAMES = 5
ROI_TRACKING_ENABLED = True
ROI_EXPAND_X = 0.45
ROI_EXPAND_TOP = 0.45
ROI_EXPAND_BOTTOM = 0.45
ROI_MIN_FACE_SCALE = 0.55
ROI_MAX_RESULTS_PER_FACE = 2

LANDMARK_SMOOTHING_ALPHA = 0.35
LANDMARK_ALPHA_JAW = 0.12
LANDMARK_ALPHA_BROW_NOSE = 0.22
LANDMARK_ALPHA_EYES_MOUTH = 0.34
LANDMARK_ALPHA_OPEN_MOUTH = 0.72
LANDMARK_MAX_POINT_JUMP_RATIO = 0.16
LANDMARK_MOUTH_MAX_POINT_JUMP_RATIO = 0.30
LANDMARK_JAW_MAX_POINT_JUMP_RATIO = 0.055
LANDMARK_JAW_BOUND_MARGIN_X = 0.08
LANDMARK_JAW_BOUND_TOP_RATIO = 0.10
LANDMARK_JAW_BOUND_BOTTOM_RATIO = 1.08
LANDMARK_JAW_EYE_HALF_WIDTH_RATIO = 1.08
LANDMARK_JAW_MIN_HALF_WIDTH_RATIO = 0.34
LANDMARK_RESET_CENTER_SHIFT = 0.35
LANDMARK_RESET_AREA_RATIO = 0.55
LANDMARK_RESET_EYE_ANGLE_DEGREES = 18.0
DISPLAY_LANDMARK_ALPHA = 0.28
DISPLAY_JAW_ALPHA = 0.13
DISPLAY_OPEN_MOUTH_ALPHA = 0.72
DISPLAY_POSE_CONTOUR_START_YAW = 8.0
DISPLAY_POSE_CONTOUR_FULL_YAW = 35.0
DISPLAY_POSE_CONTOUR_MAX_SHRINK = 0.28
DISPLAY_POSE_CONTOUR_Y_LIFT = 0.06
FACE_CHANGE_IOU_THRESHOLD = 0.25
FACE_MIN_AREA_RATIO = 0.015
FACE_MAX_AREA_RATIO = 0.75
FACE_MIN_ASPECT_RATIO = 0.65
FACE_MAX_ASPECT_RATIO = 1.45
SUDDEN_SHRINK_AREA_RATIO = 0.35
INNER_FALSE_POSITIVE_IOU = 0.90
SUDDEN_SHRINK_TRACK_AREA_RATIO = 0.55
SUDDEN_SHRINK_TRACK_CENTER_MARGIN = 0.22
SUDDEN_SHRINK_TRACK_MIN_INSIDE_RATIO = 0.35
MOUTH_FALSE_FACE_AREA_RATIO = 0.45
MOUTH_FALSE_FACE_INSIDE_RATIO = 0.72
MOUTH_FALSE_FACE_MIN_CENTER_Y = 0.42
SINGLE_FACE_MODE = False
FACE_DETECTOR_BACKEND = "haar"
YUNET_SCORE_THRESHOLD = 0.80
YUNET_NMS_THRESHOLD = 0.30
YUNET_TOP_K = 100

LBF_EXPAND_X = 0.03
LBF_EXPAND_TOP = 0.04
LBF_EXPAND_BOTTOM = 0.03
LANDMARK_MIN_INSIDE_RATIO = 0.55
LANDMARK_MIN_FACE_SPREAD_RATIO = 0.18
LANDMARK_MAX_OUTSIDE_MARGIN = 0.65
MOUTH_OPEN_RATIO = 0.10
MOUTH_OPEN_LOWER_LIP_MIN_GAP_RATIO = 0.055

HEAD_POSE_SMOOTHING_ALPHA = 0.25
HEAD_POSE_YAW_THRESHOLD = 25.0
HEAD_POSE_PITCH_THRESHOLD = 22.0
HEAD_POSE_INVERT_YAW = False
HEAD_POSE_INVERT_PITCH = True
POSE_USE_2D_YAW_FALLBACK = True
POSE_2D_YAW_SCALE = 220.0
POSE_2D_MAX_ABS_YAW = 55.0
POSE_MAX_REASONABLE_ABS_PITCH = 90.0
